learning_rate1: 0.0001
learning_rate2: 0.001
weight_decay1: 0.0001
weight_decay2: 0.0
spatial:
  use_order_constraint: true
  order_alpha_min: 0.0
  order_alpha_max: 2.0
  order_rho: 2.0
  order_window: 3